# Generated by Django 5.1.5 on 2025-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=5)),
                ('route', models.CharField(max_length=100)),
                ('boarding', models.CharField(max_length=100)),
                ('dropping', models.CharField(max_length=100)),
            ],
        ),
    ]
