# Generated by Django 5.1.5 on 2025-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('coach2', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='coach1',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
