# Generated by Django 5.1.5 on 2025-02-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_details_bus_coach1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='coach2',
            new_name='coach',
        ),
    ]
