# Generated by Django 5.1.5 on 2025-02-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_rename_coach2_details_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='boarding',
            new_name='Boarding',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='coach',
            new_name='Coach',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='destination',
            new_name='Destination',
        ),
    ]
