# Generated by Django 5.1.5 on 2025-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_rename_boarding_details_boarding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='coach1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='details',
            name='Coach',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='Date',
            field=models.DateField(),
        ),
    ]
