# Generated by Django 5.1.5 on 2025-02-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_contactinfo_alter_bus_coach1_alter_bus_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('return_date', models.DateField()),
                ('boarding', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('pref_bus', models.CharField(max_length=100)),
                ('no_of_bus', models.CharField(choices=[('ACE', 'AC Economy'), ('ACB', 'AC Business Class'), ('NAC', 'Non AC')], max_length=100)),
                ('no_of_seat', models.CharField(choices=[(27, '27 Seats'), (28, '28 Seats'), (34, '34 Seats'), (36, '36 Seats'), (40, '40 Seats')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
