# Generated by Django 5.1.5 on 2025-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_reserveinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveinfo',
            name='no_of_bus',
            field=models.CharField(choices=[('', 'Select Coach'), ('ACE', 'AC Economy'), ('ACB', 'AC Business Class'), ('NAC', 'Non AC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reserveinfo',
            name='no_of_seat',
            field=models.CharField(choices=[('', 'Select Seats'), (27, '27 Seats'), (28, '28 Seats'), (34, '34 Seats'), (36, '36 Seats'), (40, '40 Seats')], max_length=30),
        ),
    ]
