# Generated by Django 5.1.5 on 2025-02-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_alter_reserveinfo_no_of_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Coach',
            field=models.CharField(choices=[('', 'Select Coach'), ('ACE', 'AC Economy'), ('ACB', 'AC Business Class'), ('NAC', 'Non AC')], max_length=10),
        ),
    ]
